### ISSUE TITLE
Problem to run code

### ISSUE THREAD

**Issue by AliciaYuan** [yumoxu/detnet#1]
Hi, 

First, thanks a lot for the interesting work and for releasing the code.

I met some problems when trying to run the code. First, some errors occur due to misaligning between 'src/config/config_path.yml' and 'config_loader.py', specifically, proj_path including 'test_sents' (which seems useless in code) and 'label_consistency_assumption' (which seems more important) are missing.

After I "bypass" the above errors according to my understanding, a new error saying "No module named 'summ'" occurs in /src/fram/top_words.py.

Looking forward to hearing from you.

Thanks

**Comment by yumoxu** [comment]
Hi Alicia, thanks for spotting them! I have fixed these issues.

**Comment by AliciaYuan** [comment]
Thanks for updating!

I ran into another issue: AttributeError: type object 'DetNet' has no attribute 'use_top'. Could you please help me with it?

Thanks

**Comment by AliciaYuan** [comment]
And after I "bypass" the above issue, another thing came up:
Traceback (most recent call last):
  File "src/main.py", line 105, in <module>
    model = make_model(**model_paras)
  File "/media/dylanz/MyFiles/Siyang/detnet/src/frame/model.py", line 461, in make_detnet_model
    model_components['sent_det'] = SentDomDetector(**sent_det_para)
  File "/media/dylanz/MyFiles/Siyang/detnet/src/frame/detector.py", line 262, in __init__
    topic_ids = side_info['topic_ids']
KeyError: 'topic_ids'

Could you please help me solve these issues?
Thanks
