### ISSUE TITLE
Errors when running code

### ISSUE THREAD

**Issue by AliciaYuan** [yumoxu/detnet#2]
Thanks for updating!

I ran into another issue: AttributeError: type object 'DetNet' has no attribute 'use_top'. 

And after I "bypass" the above issue, another thing came up:
Traceback (most recent call last):
File "src/main.py", line 105, in
model = make_model(**model_paras)
File "/media/dylanz/MyFiles/Siyang/detnet/src/frame/model.py", line 461, in make_detnet_model
model_components['sent_det'] = SentDomDetector(**sent_det_para)
File "/media/dylanz/MyFiles/Siyang/detnet/src/frame/detector.py", line 262, in init
topic_ids = side_info['topic_ids']
KeyError: 'topic_ids'

Could you please help me solve these issues?
Thanks a lot!

**Comment by yumoxu** [comment]
Hi Alicia, domain topics were once used as side information but are not included in the final version of our model. I have fixed relevant references. Cheers!

**Comment by AliciaYuan** [comment]
@yumoxu Thanks for updating! The code works now.

One more question, how many GPUs did you use to train the model? And how long does the training take? Thanks a lot!

**Comment by yumoxu** [comment]
I used 4 GTX1080; It took just a couple of hours (<10), if my recall is right.

**Comment by AliciaYuan** [comment]
@yumoxu  Got it, thanks!
